# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
import os
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 133)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 591, 41))
        self.label.setStyleSheet("background: #221F1F;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Particle")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 90, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 89, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Particle")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Particle")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 50, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Particle")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 50, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Particle")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.hide_or_show()
    def hide_or_show(self):
        self.pushButton.clicked.connect(self.go)
        self.pushButton_2.clicked.connect(self.show)
        self.pushButton_3.clicked.connect(self.hide)
    def hide(self):
        self.pushButton.setText("Hide")
    def show(self):
        self.pushButton.setText("Show")
    def go(self):
        file = self.lineEdit.text()
        if file != "" or file != " " or file != "  ":
            if self.pushButton.text() == "Hide":
                os.system(f'attrib +h "{file}"')
            else:
                os.system(f'attrib -h "{file}"')
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hi-Shi"))
        self.label_2.setText(_translate("MainWindow", "Hide or Show file"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter file link..."))
        self.label_3.setText(_translate("MainWindow", "File"))
        self.pushButton.setText(_translate("MainWindow", "Hide"))
        self.pushButton_2.setText(_translate("MainWindow", "Show"))
        self.pushButton_3.setText(_translate("MainWindow", "Hide"))
import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())
